# Generated by Django 4.1.2 on 2022-11-01 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_post_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='streak',
            field=models.IntegerField(default=1),
        ),
    ]
