# Generated by Django 4.1.2 on 2022-11-01 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_post_updated_on_alter_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created_time',
            field=models.TimeField(auto_now=True),
        ),
    ]
